#docker-compose.yml
version: '3'
services:
  database-container:
    container_name: database-container
    image: mongo:4.4.7-focal
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

volumes:
  db-data: